name: CI
on:
  - push
jobs:
  test:
    name: ${{ matrix.solver }} tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.5'
        os:
          - ubuntu-latest
        arch:
          - x64
        solver:
          - SCS
          - ProxSDP
          - COSMO
          - Tulip
          - SDPA
          - CSDP
          - SDPA_GMP
          - ECOS
          - Hypatia
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - run: |
          julia --project=${{ matrix.solver }} -e '
            using Pkg;
            Pkg.add(PackageSpec(url="https://github.com/ericphanson/TableTestSets.jl"));
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate();'
      - run: julia --project=${{ matrix.solver }} ${{ matrix.solver }}/test.jl
      - name: Commit test results
        run: |
          set +e
          git config --global user.name 'Eric P. Hanson'
          git config --global user.email '5846501+ericphanson@users.noreply.github.com'
          git pull
          git add docs/src/${{ matrix.solver }}.md
          if [ -n "$( git diff --cached --exit-code)" ]; then
            git commit -m "Automated update for ${{ matrix.solver }}"
            git push
          fi
          if [ $? -ne 0 ]; then
            n=0
            until [ $n -ge 10 ]
            do
              git pull && git push && break
              n=$[$n+1]
              sleep 2
            done
          fi
  docs:
    needs: test
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.5'
      - run: |
          julia --project=docs -e '
            using Pkg;
            Pkg.add(PackageSpec(url="https://github.com/ericphanson/TableTestSets.jl"));
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate();'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
